export const FEATURES = [
  // Core Modules
  {
    id: 'student-management',
    title: 'Student Management',
    description: 'Complete student lifecycle management with registration, profiles, attendance, and performance tracking.',
    icon: 'bx-user',
    gradient: 'bg-blue-500/20 border border-blue-500/30',
    slug: 'student-management',
    category: 'Core Modules',
    benefits: [
      'Complete student registration and profile management',
      'Real-time attendance tracking and monitoring',
      'Academic performance tracking and analytics',
      'Document management and storage',
      'Parent communication and notifications',
    ],
    capabilities: [
      'Student enrollment and admission processing',
      'Academic records and transcript management',
      'Attendance marking and reporting',
      'Grade and assessment tracking',
      'Medical records and emergency contacts',
      'Fee management and payment tracking',
    ],
    faq: [
      { q: 'Can we migrate existing student data?', a: 'Yes, we support CSV import and guided data migration.' },
      { q: 'Is student data secure?', a: 'All student records are encrypted and comply with data protection regulations.' },
      { q: 'Can parents access student information?', a: 'Yes, parents can view their child\'s progress through the parent portal.' },
    ],
  },
  {
    id: 'hostel-management',
    title: 'Hostel Management',
    description: 'Manage hostels, rooms, occupancy, maintenance, and student allocations with ease.',
    icon: 'bx-home',
    gradient: 'bg-blue-500/20 border border-blue-500/30',
    slug: 'hostel-management',
    category: 'Core Modules',
    benefits: [
      'Centralized hostel and room inventory',
      'Real-time occupancy and allocation tracking',
      'Maintenance requests and ticketing',
      'Visitor logs and check-in/check-out',
      'Fee management and dues tracking',
    ],
    capabilities: [
      'Room allocation and swap workflows',
      'Occupancy dashboards and reports',
      'Maintenance triage and SLA tracking',
      'Hostel fee invoicing and reminders',
      'Gate pass and visitor management',
      'Emergency contacts and compliance',
    ],
    faq: [
      { q: 'Can we bulk-assign rooms?', a: 'Yes, you can bulk-allocate and import allocations via CSV.' },
      { q: 'Can students request room change?', a: 'Yes, with approval workflows for wardens/admins.' },
    ],
  },
  {
    id: 'attendance-tracking',
    title: 'Attendance Tracking',
    description: 'Real-time attendance monitoring with automated reports and parent notifications.',
    icon: 'bx-calendar-check',
    gradient: 'bg-blue-500/20 border border-blue-500/30',
    slug: 'attendance-tracking',
    category: 'Core Modules',
    benefits: [
      'Instant daily roll calls with one-click status',
      'Automated alerts to parents for absences/tardies',
      'Weekly and monthly compliance reports',
      'Real-time attendance dashboard',
      'Mobile-friendly attendance marking',
    ],
    capabilities: [
      'Homeroom and period-based attendance',
      'CSV/PDF export for audits',
      'Mobile-friendly teacher view',
      'Automated parent notifications',
      'Attendance analytics and trends',
      'Integration with student management',
    ],
    faq: [
      { q: 'Does it work offline?', a: 'Yes, cached entries sync when connection resumes.' },
      { q: 'Can parents receive attendance alerts?', a: 'Yes, parents get real-time notifications for attendance issues.' },
    ],
  },
  {
    id: 'grade-management',
    title: 'Grade Management',
    description: 'Digital gradebook with automated calculations and progress tracking.',
    icon: 'bx-award',
    gradient: 'bg-blue-500/20 border border-blue-500/30',
    slug: 'grade-management',
    category: 'Core Modules',
    benefits: [
      'Weighted categories and custom grading scales',
      'Auto-calculated term and final grades',
      'Parent and student portals for transparency',
      'Grade analytics and performance insights',
      'Automated report generation',
    ],
    capabilities: [
      'Rubrics and outcomes',
      'Bulk grade entry and import',
      'Publish progress reports',
      'Grade distribution analysis',
      'Performance trend tracking',
      'Integration with assessment tools',
    ],
    faq: [
      { q: 'Can we customize grading scales?', a: 'Yes, you can set up custom grading scales and categories.' },
      { q: 'Are grades automatically calculated?', a: 'Yes, the system automatically calculates weighted averages and final grades.' },
    ],
  },
  {
    id: 'parent-portal',
    title: 'Parent Portal',
    description: 'Secure portal for parents to view progress, attendance, and communicate with teachers.',
    icon: 'bx-shield',
    gradient: 'bg-blue-500/20 border border-blue-500/30',
    slug: 'parent-portal',
    category: 'Core Modules',
    benefits: [
      'Single login for multiple children',
      'Real-time notifications and messaging',
      'Payments and permissions (optional add-ons)',
      'Academic progress monitoring',
      'Direct communication with teachers',
    ],
    capabilities: [
      'Announcements and calendars',
      'Downloadable reports and certificates',
      'Fee payment and tracking',
      'Parent-teacher conference scheduling',
      'Student performance analytics',
      'Emergency contact management',
    ],
    faq: [
      { q: 'Can parents access multiple children?', a: 'Yes, parents can view all their children from one account.' },
      { q: 'Is the parent portal secure?', a: 'Yes, all parent data is encrypted and access is role-based.' },
    ],
  },
  {
    id: 'course-management',
    title: 'Course Management',
    description: 'Organize courses, subjects, timetables, and curriculum with flexible scheduling.',
    icon: 'bx-book',
    gradient: 'bg-blue-500/20 border border-blue-500/30',
    slug: 'course-management',
    category: 'Core Modules',
    benefits: [
      'Drag-and-drop timetable builder',
      'Manage sections, rooms, and capacities',
      'Prerequisites and co-requisites',
      'Curriculum planning and tracking',
      'Resource allocation and management',
    ],
    capabilities: [
      'Teacher assignments and load balance',
      'Syllabus templates and resources',
      'Course catalog management',
      'Class scheduling and conflicts',
      'Room and resource booking',
      'Academic calendar integration',
    ],
    faq: [
      { q: 'Can we import existing timetables?', a: 'Yes, we support CSV import for existing schedules.' },
      { q: 'How does conflict detection work?', a: 'The system automatically detects scheduling conflicts and suggests alternatives.' },
    ],
  },
  {
    id: 'analytics-reports',
    title: 'Analytics & Reports',
    description: 'Dashboards and detailed reports for attendance, performance, and engagement.',
    icon: 'bx-bar-chart',
    gradient: 'bg-blue-500/20 border border-blue-500/30',
    slug: 'analytics-reports',
    category: 'Core Modules',
    benefits: [
      'KPIs at a glance with drill-downs',
      'Export to CSV/PDF for stakeholders',
      'Comparative trends across terms/years',
      'Real-time data visualization',
      'Customizable dashboard widgets',
    ],
    capabilities: [
      'Attendance heatmaps',
      'Grade distribution charts',
      'Cohort analysis',
      'Performance trend analysis',
      'Custom report builder',
      'Data export and sharing',
    ],
    faq: [
      { q: 'What types of reports are available?', a: 'We provide attendance, academic performance, and engagement reports.' },
      { q: 'Can reports be customized?', a: 'Yes, you can create custom reports with specific metrics and filters.' },
    ],
  },
  {
    id: 'faculty-management',
    title: 'Faculty Management',
    description: 'Comprehensive faculty profiles, course management, and grade upload system for educators.',
    icon: 'bx-chalkboard',
    gradient: 'bg-blue-500/20 border border-blue-500/30',
    slug: 'faculty-management',
    category: 'Core Modules',
    benefits: [
      'Faculty profile and qualification management',
      'Course assignment and scheduling',
      'Grade upload and management system',
      'Teaching load and workload tracking',
      'Performance evaluation and feedback',
    ],
    capabilities: [
      'Faculty registration and profile creation',
      'Course and subject assignment',
      'Grade entry and submission',
      'Teaching schedule management',
      'Student evaluation and feedback',
      'Professional development tracking',
    ],
    faq: [
      { q: 'Can faculty upload grades in bulk?', a: 'Yes, faculty can upload grades via CSV or individual entry.' },
      { q: 'Is there a mobile app for faculty?', a: 'Yes, faculty can access the system through mobile-responsive web interface.' },
    ],
  },
  {
    id: 'admin-dashboard',
    title: 'Admin Dashboard',
    description: 'Complete system administration with analytics, user management, and comprehensive reporting.',
    icon: 'bx-cog',
    gradient: 'bg-blue-500/20 border border-blue-500/30',
    slug: 'admin-dashboard',
    category: 'Core Modules',
    benefits: [
      'Complete system administration and control',
      'Real-time analytics and insights',
      'User management and role assignment',
      'System configuration and settings',
      'Comprehensive reporting and exports',
    ],
    capabilities: [
      'User account management and permissions',
      'System configuration and customization',
      'Analytics dashboard and reporting',
      'Data backup and recovery',
      'System monitoring and maintenance',
      'Integration management',
    ],
    faq: [
      { q: 'What analytics are available?', a: 'We provide student performance, attendance, faculty workload, and system usage analytics.' },
      { q: 'Can we customize the dashboard?', a: 'Yes, admins can customize dashboard widgets and reports.' },
    ],
  },
  // Admission System
  {
    id: 'admission-system',
    title: 'Admission System',
    description: 'Public application submission with admin approval workflow and status tracking.',
    icon: 'bx-file-plus',
    gradient: 'bg-orange-500/20 border border-orange-500/30',
    slug: 'admission-system',
    category: 'Admission System',
    benefits: [
      'Public application submission without registration',
      'OTP-based applicant authentication',
      'Admin review and approval workflow',
      'Real-time application status tracking',
      'Course and fee information display',
    ],
    capabilities: [
      'Online application form submission',
      'Document upload and verification',
      'Application review and approval process',
      'Status tracking with admission ID',
      'Course catalog and fee structure',
      'College information and facilities',
    ],
    faq: [
      { q: 'Can anyone apply without creating an account?', a: 'Yes, the admission system allows public applications without registration.' },
      { q: 'How can applicants track their application?', a: 'Applicants can track status using their admission ID (admid).' },
    ],
  },
  // Communication
  {
    id: 'real-time-chat',
    title: 'Real-time Chat',
    description: 'WebSocket-based messaging system for seamless communication between students and faculty.',
    icon: 'bx-message-dots',
    gradient: 'bg-teal-500/20 border border-teal-500/30',
    slug: 'real-time-chat',
    category: 'Communication',
    benefits: [
      'Instant messaging between students and faculty',
      'Group chat for classes and projects',
      'File sharing and media support',
      'Message history and search',
      'Online presence indicators',
    ],
    capabilities: [
      'One-on-one messaging',
      'Group chat creation and management',
      'File and document sharing',
      'Message threading and replies',
      'Emoji and reaction support',
      'Message encryption and security',
    ],
    faq: [
      { q: 'Is the chat system secure?', a: 'Yes, all messages are encrypted and stored securely.' },
      { q: 'Can faculty moderate group chats?', a: 'Yes, faculty have moderation tools for class group chats.' },
    ],
  },
  {
    id: 'notification-system',
    title: 'Notification System',
    description: 'Real-time notifications for all users with email, SMS, and in-app messaging.',
    icon: 'bx-bell',
    gradient: 'bg-teal-500/20 border border-teal-500/30',
    slug: 'notification-system',
    category: 'Communication',
    benefits: [
      'Real-time notifications for all users',
      'Multi-channel delivery (email, SMS, in-app)',
      'Customizable notification preferences',
      'Scheduled and automated notifications',
      'Notification history and tracking',
    ],
    capabilities: [
      'Email notification delivery',
      'SMS integration for urgent alerts',
      'In-app notification center',
      'Push notifications for mobile',
      'Notification scheduling and automation',
      'User preference management',
    ],
    faq: [
      { q: 'Can users customize notification preferences?', a: 'Yes, users can choose which notifications to receive and how.' },
      { q: 'Are notifications sent in real-time?', a: 'Yes, notifications are delivered instantly via WebSocket technology.' },
    ],
  },
];

export const WHY_US_FEATURES = [
  {
    title: "Save time for teachers and admins",
    description: "Automate routine tasks and reduce administrative burden, allowing educators to focus more on teaching and student engagement.",
    icon: "bx-time-five",
    gradient: "bg-white/10 border border-white/20",
  },
  {
    title: "Easy for students to track performance",
    description: "Provide students with easy access to their academic records, attendance, and progress reports, empowering them to take ownership of their learning journey.",
    icon: "bx-bar-chart-alt-2",
    gradient: "bg-white/10 border border-white/20",
  },
  {
    title: "Simplified communication with parents",
    description: "Facilitate seamless communication between teachers, students, and parents through integrated messaging and notification systems.",
    icon: "bx-message-dots",
    gradient: "bg-white/10 border border-white/20",
  },
  {
    title: "Secure and reliable",
    description: "Ensure data privacy and security with robust encryption and compliance with educational regulations.",
    icon: "bx-lock-alt",
    gradient: "bg-white/10 border border-white/20",
  },
  {
    title: "Course Management",
    description: "Organize courses, subjects, and curriculum with flexible scheduling options.",
    icon: "bx-book-open",
    gradient: "bg-white/10 border border-white/20",
  },
  {
    title: "Analytics & Reports",
    description: "Comprehensive analytics dashboard with detailed reports and insights.",
    icon: "bx-analyse",
    gradient: "bg-white/10 border border-white/20",
  },
];
